[Service]
StartupMsg = "UniOS Alarm Collector Started"
Target = "127.0.0.1"
Port = 8002
Transport = "udp"
Timeout = 5
Retries = 2
ContextName = ""
Community = "public"
Oids = []

[SNMP]
Securitylevel = "AuthNoPriv" # AuthPriv NoAuthNoPriv AuthNoPriv
UserName = "nms2-admin"
AuthPassword = "zhongying123456" # password
PrivPassword = "zhongying123456" #password
AuthProtocol = "SHA512" # MD5   SHA   SHA224    SHA256    SHA384    SHA512
PrivProtocol = "AES256" # DES    AES    AES192   AES256   AES192C    AES256C

[Logging]
IsJSON = false
Level = "info"
KeepInContainer = false
MaxSize = 1024